# Labels definition for repository management
# YAML must be a top-level array (no root key)
- name: "type: bug"
  color: "d73a4a"
  description: "버그 제보"
- name: "type: feature"
  color: "a2eeef"
  description: "기능 제안"
- name: "type: improvement"
  color: "0366d6"
  description: "개선/리팩토링 제안"
- name: "type: docs"
  color: "0075ca"
  description: "문서 관련"
- name: "type: data"
  color: "0e8a16"
  description: "데이터 수정/추가"
- name: "type: crawler"
  color: "5319e7"
  description: "크롤러 관련"
- name: "type: question"
  color: "d4c5f9"
  description: "질문/문의"
- name: "type: discussion"
  color: "fef2c0"
  description: "논의"

- name: "area: crawler"
  color: "7057ff"
  description: "크롤러"
- name: "area: api"
  color: "1d76db"
  description: "API/서버"
- name: "area: web"
  color: "0b6e99"
  description: "웹 프론트엔드"
- name: "area: backend"
  color: "5319e7"
  description: "백엔드"
- name: "area: data"
  color: "006b75"
  description: "데이터 파이프라인/저장소"
- name: "area: recommendation"
  color: "c2e0c6"
  description: "추천/검색"
- name: "area: community"
  color: "0052cc"
  description: "커뮤니티/리뷰"

- name: "priority: high"
  color: "b60205"
  description: "높음 - 빠른 대응 필요"
- name: "priority: medium"
  color: "fbca04"
  description: "보통"
- name: "priority: low"
  color: "0e8a16"
  description: "낮음"

- name: "status: needs triage"
  color: "d4c5f9"
  description: "분류 필요"
- name: "status: in progress"
  color: "1d76db"
  description: "진행 중"
- name: "status: needs review"
  color: "c5def5"
  description: "리뷰 필요"
- name: "status: blocked"
  color: "b60205"
  description: "블로킹됨"

- name: "good first issue"
  color: "7057ff"
  description: "초보자 친화적"
- name: "help wanted"
  color: "008672"
  description: "도움 필요"
- name: "performance"
  color: "e99695"
  description: "성능 관련"
- name: "security"
  color: "ee0701"
  description: "보안 관련"
- name: "refactor"
  color: "0366d6"
  description: "리팩토링"
- name: "tests"
  color: "5319e7"
  description: "테스트"
- name: "design"
  color: "fbca04"
  description: "디자인/UX"
- name: "dependencies"
  color: "0366d6"
  description: "의존성 업데이트"
- name: "breaking change"
  color: "000000"
  description: "하위 호환성 영향"
